// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomepageDocumentDataSlicesSlice =
  | CustomerReviewsSlice
  | OurServicesSlice
  | FeaturedProductsSlice
  | HeroBannerSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type PageDocumentDataSlicesSlice = AboutSlice;

/**
 * Content for page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Settings → NavLinks*
 */
export interface SettingsDocumentDataNavlinksItem {
  /**
   * Link field in *Settings → NavLinks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navlinks[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Label field in *Settings → NavLinks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navlinks[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Name field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * SubName field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.subname
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subname: prismic.KeyTextField;

  /**
   * NavLinks field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navlinks[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navlinks: prismic.GroupField<Simplify<SettingsDocumentDataNavlinksItem>>;

  /**
   * CtaLink field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.ctalink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  ctalink: prismic.LinkField;

  /**
   * CtaLabel field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.ctalabel
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ctalabel: prismic.KeyTextField;

  /**
   * FooterText field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footertext
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  footertext: prismic.KeyTextField;

  /**
   * InstaLink field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.instalink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  instalink: prismic.LinkField;

  /**
   * WhatsappLink field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.whatsapplink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  whatsapplink: prismic.LinkField /**
   * MetaTitle field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.metatitle
   * - **Tab**: MetaData
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  metatitle: prismic.KeyTextField;

  /**
   * MetaDescription field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.metadescription
   * - **Tab**: MetaData
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  metadescription: prismic.KeyTextField;

  /**
   * OgImage field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.ogimage
   * - **Tab**: MetaData
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  ogimage: prismic.ImageField<never>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | HomepageDocument
  | PageDocument
  | SettingsDocument;

/**
 * Primary content in *About → Default → Primary*
 */
export interface AboutSliceDefaultPrimary {
  /**
   * ProfileImage field in *About → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.profileimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  profileimage: prismic.ImageField<never>;

  /**
   * Heading field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * BodyDescription field in *About → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.bodydescription
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bodydescription: prismic.RichTextField;

  /**
   * ButtonText field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.buttontext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttontext: prismic.KeyTextField;

  /**
   * ButtonLink field in *About → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.buttonlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonlink: prismic.LinkField;
}

/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *About*
 */
type AboutSliceVariation = AboutSliceDefault;

/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: About
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSlice = prismic.SharedSlice<"about", AboutSliceVariation>;

/**
 * Item in *CustomerReviews → Default → Primary → CustomerReviews*
 */
export interface CustomerReviewsSliceDefaultPrimaryCustomerreviewsItem {
  /**
   * ReviewText field in *CustomerReviews → Default → Primary → CustomerReviews*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_reviews.default.primary.customerreviews[].reviewtext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  reviewtext: prismic.KeyTextField;

  /**
   * ReviewAuthor field in *CustomerReviews → Default → Primary → CustomerReviews*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_reviews.default.primary.customerreviews[].reviewauthor
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  reviewauthor: prismic.KeyTextField;

  /**
   * ReviewImage field in *CustomerReviews → Default → Primary → CustomerReviews*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_reviews.default.primary.customerreviews[].reviewimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  reviewimage: prismic.ImageField<never>;
}

/**
 * Primary content in *CustomerReviews → Default → Primary*
 */
export interface CustomerReviewsSliceDefaultPrimary {
  /**
   * SectionTitle field in *CustomerReviews → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_reviews.default.primary.sectiontitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sectiontitle: prismic.KeyTextField;

  /**
   * SectionDescription field in *CustomerReviews → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_reviews.default.primary.sectiondescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sectiondescription: prismic.KeyTextField;

  /**
   * CustomerReviews field in *CustomerReviews → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_reviews.default.primary.customerreviews[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  customerreviews: prismic.GroupField<
    Simplify<CustomerReviewsSliceDefaultPrimaryCustomerreviewsItem>
  >;
}

/**
 * Default variation for CustomerReviews Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CustomerReviewsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CustomerReviewsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CustomerReviews*
 */
type CustomerReviewsSliceVariation = CustomerReviewsSliceDefault;

/**
 * CustomerReviews Shared Slice
 *
 * - **API ID**: `customer_reviews`
 * - **Description**: CustomerReviews
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CustomerReviewsSlice = prismic.SharedSlice<
  "customer_reviews",
  CustomerReviewsSliceVariation
>;

/**
 * Item in *FeaturedProducts → Default → Primary → FeaturedProducts*
 */
export interface FeaturedProductsSliceDefaultPrimaryFeaturedproductsItem {
  /**
   * ProductImage field in *FeaturedProducts → Default → Primary → FeaturedProducts*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.default.primary.featuredproducts[].productimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  productimage: prismic.ImageField<never>;

  /**
   * ProductTitle field in *FeaturedProducts → Default → Primary → FeaturedProducts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.default.primary.featuredproducts[].producttitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  producttitle: prismic.KeyTextField;

  /**
   * ProductBrand field in *FeaturedProducts → Default → Primary → FeaturedProducts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.default.primary.featuredproducts[].productbrand
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  productbrand: prismic.KeyTextField;

  /**
   * ProductDescription field in *FeaturedProducts → Default → Primary → FeaturedProducts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.default.primary.featuredproducts[].productdescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  productdescription: prismic.KeyTextField;

  /**
   * ProductPrice field in *FeaturedProducts → Default → Primary → FeaturedProducts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.default.primary.featuredproducts[].productprice
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  productprice: prismic.KeyTextField;
}

/**
 * Primary content in *FeaturedProducts → Default → Primary*
 */
export interface FeaturedProductsSliceDefaultPrimary {
  /**
   * SectionTitle field in *FeaturedProducts → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.default.primary.sectiontitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sectiontitle: prismic.KeyTextField;

  /**
   * SectionDescription field in *FeaturedProducts → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.default.primary.sectiondescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sectiondescription: prismic.KeyTextField;

  /**
   * FeaturedProducts field in *FeaturedProducts → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.default.primary.featuredproducts[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  featuredproducts: prismic.GroupField<
    Simplify<FeaturedProductsSliceDefaultPrimaryFeaturedproductsItem>
  >;
}

/**
 * Default variation for FeaturedProducts Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedProductsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedProductsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeaturedProducts*
 */
type FeaturedProductsSliceVariation = FeaturedProductsSliceDefault;

/**
 * FeaturedProducts Shared Slice
 *
 * - **API ID**: `featured_products`
 * - **Description**: FeaturedProducts
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedProductsSlice = prismic.SharedSlice<
  "featured_products",
  FeaturedProductsSliceVariation
>;

/**
 * Primary content in *HeroBanner → Default → Primary*
 */
export interface HeroBannerSliceDefaultPrimary {
  /**
   * Heading field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Subheading field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * ExploreCTA field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.explorecta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  explorecta: prismic.LinkField;

  /**
   * HeroImage field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.heroimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  heroimage: prismic.ImageField<never>;
}

/**
 * Default variation for HeroBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroBanner*
 */
type HeroBannerSliceVariation = HeroBannerSliceDefault;

/**
 * HeroBanner Shared Slice
 *
 * - **API ID**: `hero_banner`
 * - **Description**: HeroBanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBannerSlice = prismic.SharedSlice<
  "hero_banner",
  HeroBannerSliceVariation
>;

/**
 * Item in *NewOffers → Default → Primary → Offers*
 */
export interface NewOffersSliceDefaultPrimaryOffertitleItem {
  /**
   * OfferTitle field in *NewOffers → Default → Primary → Offers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: new_offers.default.primary.offertitle[].offertitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  offertitle: prismic.KeyTextField;

  /**
   * OfferDescription field in *NewOffers → Default → Primary → Offers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: new_offers.default.primary.offertitle[].offerdescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  offerdescription: prismic.KeyTextField;

  /**
   * OfferImage field in *NewOffers → Default → Primary → Offers*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: new_offers.default.primary.offertitle[].offerimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  offerimage: prismic.ImageField<never>;
}

/**
 * Primary content in *NewOffers → Default → Primary*
 */
export interface NewOffersSliceDefaultPrimary {
  /**
   * SectionTitle field in *NewOffers → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: new_offers.default.primary.sectiontitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sectiontitle: prismic.KeyTextField;

  /**
   * SectionDescription field in *NewOffers → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: new_offers.default.primary.sectiondescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sectiondescription: prismic.KeyTextField;

  /**
   * Offers field in *NewOffers → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: new_offers.default.primary.offertitle[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  offertitle: prismic.GroupField<
    Simplify<NewOffersSliceDefaultPrimaryOffertitleItem>
  >;

  /**
   * OfferCTA field in *NewOffers → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: new_offers.default.primary.offercta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  offercta: prismic.LinkField;
}

/**
 * Default variation for NewOffers Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewOffersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewOffersSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NewOffers*
 */
type NewOffersSliceVariation = NewOffersSliceDefault;

/**
 * NewOffers Shared Slice
 *
 * - **API ID**: `new_offers`
 * - **Description**: NewOffers
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewOffersSlice = prismic.SharedSlice<
  "new_offers",
  NewOffersSliceVariation
>;

/**
 * Item in *OurServices → Default → Primary → Services*
 */
export interface OurServicesSliceDefaultPrimaryServicesItem {
  /**
   * ServiceTitle field in *OurServices → Default → Primary → Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_services.default.primary.services[].servicetitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  servicetitle: prismic.KeyTextField;

  /**
   * ServiceDescription field in *OurServices → Default → Primary → Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_services.default.primary.services[].servicedescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  servicedescription: prismic.KeyTextField;
}

/**
 * Primary content in *OurServices → Default → Primary*
 */
export interface OurServicesSliceDefaultPrimary {
  /**
   * SectionTitle field in *OurServices → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_services.default.primary.sectiontitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sectiontitle: prismic.KeyTextField;

  /**
   * SectionDescription field in *OurServices → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_services.default.primary.sectiondescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sectiondescription: prismic.KeyTextField;

  /**
   * Services field in *OurServices → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: our_services.default.primary.services[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  services: prismic.GroupField<
    Simplify<OurServicesSliceDefaultPrimaryServicesItem>
  >;

  /**
   * serviceCTA field in *OurServices → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: our_services.default.primary.servicecta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  servicecta: prismic.LinkField;
}

/**
 * Default variation for OurServices Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurServicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OurServicesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OurServices*
 */
type OurServicesSliceVariation = OurServicesSliceDefault;

/**
 * OurServices Shared Slice
 *
 * - **API ID**: `our_services`
 * - **Description**: OurServices
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurServicesSlice = prismic.SharedSlice<
  "our_services",
  OurServicesSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavlinksItem,
      AllDocumentTypes,
      AboutSlice,
      AboutSliceDefaultPrimary,
      AboutSliceVariation,
      AboutSliceDefault,
      CustomerReviewsSlice,
      CustomerReviewsSliceDefaultPrimaryCustomerreviewsItem,
      CustomerReviewsSliceDefaultPrimary,
      CustomerReviewsSliceVariation,
      CustomerReviewsSliceDefault,
      FeaturedProductsSlice,
      FeaturedProductsSliceDefaultPrimaryFeaturedproductsItem,
      FeaturedProductsSliceDefaultPrimary,
      FeaturedProductsSliceVariation,
      FeaturedProductsSliceDefault,
      HeroBannerSlice,
      HeroBannerSliceDefaultPrimary,
      HeroBannerSliceVariation,
      HeroBannerSliceDefault,
      NewOffersSlice,
      NewOffersSliceDefaultPrimaryOffertitleItem,
      NewOffersSliceDefaultPrimary,
      NewOffersSliceVariation,
      NewOffersSliceDefault,
      OurServicesSlice,
      OurServicesSliceDefaultPrimaryServicesItem,
      OurServicesSliceDefaultPrimary,
      OurServicesSliceVariation,
      OurServicesSliceDefault,
    };
  }
}
