import { Inter } from "next/font/google";
import "@/styles/globals.css";
import styles from "@/styles/page.module.css";

import FooterComponent from "@/components/FooterComponent";
import HeaderComponent from "@/components/HeaderComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mobile Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className={styles.main}>
          <HeaderComponent />
          {children}
        </main>
        <FooterComponent />
      </body>
    </html>
  );
}
