// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  customer_reviews: dynamic(() => import("./CustomerReviews")),
  featured_products: dynamic(() => import("./FeaturedProducts")),
  hero_banner: dynamic(() => import("./HeroBanner")),
  our_services: dynamic(() => import("./OurServices")),
};
