// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  featured_products: dynamic(() => import("./FeaturedProducts")),
  hero_banner: dynamic(() => import("./HeroBanner")),
};
